### ISSUE TITLE
Error when I run convert.py

### ISSUE THREAD

**Issue by chenchix** [ghtalpo/amazfit_verge_lite_tools#2]
$ python3 convert.py gtr47
GTR source
Traceback (most recent call last):
  File "convert.py", line 112, in <module>
    Converter().resizePng(inputFileName)
  File "convert.py", line 89, in resizePng
    self.resizeJson(full_path)
  File "convert.py", line 53, in resizeJson
    self.patchTree(tree)
  File "convert.py", line 43, in patchTree
    value = tree[k] 
TypeError: list indices must be integers or slices, not dict

**Comment by chenchix** [comment]
It seems it is failing with json files like this:
[
  {
    "Time": {
      "Year": 2019,
      "Month": 1,
      "Day": 7,
      "Hour": 0,
      "Minute": 0,
...

**Comment by ghtalpo** [comment]
can you provide link for the gtr watchface?

**Comment by chenchix** [comment]
I didn't know how i closed the issue.

Here you have the file
https://drive.google.com/file/d/1R0uKtmxlsEHh2GKBCnFGW1y_HACGDvsW/view?usp=sharing

I have fixed it adding this

```
    def resizeJson(self, json_path):
        tree = self.loadJson(json_path)
        **if not 'Background' in tree:
            return**
        self.patchTree(tree)
        self.saveJson(json_path, tree)

```

To apply only to valids json.

**Comment by ghtalpo** [comment]
added your patch at 7e57acc

thanks
